Room_Reservation/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path("admin/", admin.site.urls),
                  path("accounts/", include('accounts.urls', namespace="accounts")),
                  path("", include('home.urls', namespace="home")),
                  path("reservation/", include('reservation.urls', namespace="reservation"))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name="signup"),
    path('login/', views.login_attempt, name="login"),
    path('otp/', views.check_otp, name="otp"),
    path('logout/', views.user_logout, name="logout"),
    path('profile/<uuid:pk>/', views.user_profile, name="profile"),
    path('join_group/<uuid:pk>/', views.add_to_group, name="join_group"),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name="home"),
]

reservation/urls.py
from django.urls import path
from . import views

app_name = 'reservation'

urlpatterns = [
    path('rooms/', views.EmptyRoomListView.as_view(), name='rooms'),
    path('room_detail/<uuid:room_id>/', views.room_detail, name='room_detail'),
    path('add_comment/<uuid:room_id>/', views.add_comment, name='add_comment'),
    path('reserve_room/<uuid:room_id>/', views.reserve_room, name='reserve_room'),
]

templates/main.html
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <!-- jquery -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <title>Room Reservation</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light container">
    <a class="navbar-brand" href="{% url 'home:home' %}">Room Reservation</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item active ml-5 mb-2">
                <a class="btn btn-primary" href="{% url 'home:home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item ml-5 mb-2">
                    <a class="btn btn-warning" href="{% url 'accounts:logout' %}">LogOut</a>
                </li>
                <li class="nav-item ml-5 mb-2">
                    <a class="btn btn-warning" href="{% url 'reservation:rooms' %}">Rooms</a>
                </li>
                <li class="nav-item ml-5 mb-2">
                    <a class="btn btn-warning" href="{% url 'accounts:join_group' request.user.id %}">Groups</a>
                </li>
                <li class="nav-item ml-5 mb-2">
                    <a class="btn btn-warning" href="{% url 'accounts:profile' request.user.id %}">Profile</a>
                </li>
            {% else %}
                <li class="nav-item ml-5 mb-2">
                    <a class="btn btn-warning" href="{% url 'accounts:signup' %}">SignUp</a>
                </li>
                <li class="nav-item ml-5 mb-2">
                    <a class="btn btn-warning" href="{% url 'accounts:login' %}">LogIn</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>
<div class="container mt-5">
    {% block content %}
    {% endblock %}
</div>
{# scripts #}
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>
</html>